Fixed #155 - Add 'Comment Template' to comment logic block.
visualpython/visualpython pull request #210
Opened 2023-04-04 15:18 UTC by Minku-Koo

- Add comment template on logic block
- Templates are consisting of default, class and method

2023-04-04 15:20 UTC, Minku-Koo commented
Add 'Comment Template'

2023-04-06 05:19 UTC, minjk-bl requested changes
Hello, thank you for the changes you've made, but your repository is not rebased with the current commits. 

You should first fetch & rebase your local repo using 
- `git fetch upstream`  
- `git rebase upstream/devops`

Then push it to your forked-repository using
- `git push origin devops`

In this pull-request, many past-codes are remaining yet. Merging `Comment.js` file is only needed for your request. 

* After you do fetch -> rebase -> push, then let us know to review this PR again. Thanks :)

2023-04-06 05:19 UTC, minjk-bl commented on visualpython/js/m_logic/Comment.js
It works well :)

2023-04-07 17:47 UTC, Minku-Koo commented
Thank you for your help.
I create new PR, so close this PR.

2023-04-07 17:47 UTC, closed without merging